# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Make Test

on:
  push:
    branches: [ "wsdt/make-works" ] #change later
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Build project ${{ matrix.node-version }}
      uses: borales/actions-yarn@v3.0.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: curl -L https://foundry.paradigm.xyz | bash
    - run: source /home/runner/.bashrc
    - run: foundryup
    - run: yarn
    - run: yarn build
    - run: make
